### ISSUE TITLE
Streaming support

### ISSUE THREAD

**Issue by myl7** [httptoolkit/brotli-wasm#10]
Currently WASM to/from JS of `brotli-wasm` uses `UInt8Array` to pass data, which requires all data loaded into memory in advance. It is OK for small files (TBH it is common for Brotli) but as for big files such as > 1G, this will cause a huge memory usage.

`brotli` crate provides steaming ways such as `Compressor` writer to (de)compress data piece by piece. It would be nice for the package to include them.

I am the maintainer of [`brotli-dec-wasm`](https://github.com/ustclug-dev/brotli-dec-wasm) and a streaming binding implementation is included in it. If the feature is recognized as required, I would be willing to giving a PR to implement the feature for the repo.

**Comment by pimterry** [comment]
Sure, that'd be great! If you have time I'm definitely open to a PR to add this.
