### ISSUE TITLE
Chunking support for large files

### ISSUE THREAD

**Issue by willfarrell** [httptoolkit/brotli-wasm#14]
The ability, or an example if already supported (via buffer.write?), to allow NodeJS/WebStream to be build around it.

Example: https://github.com/Daninet/hash-wasm#advanced-usage-with-streaming-input

**Comment by pimterry** [comment]
Streaming support is available - there's some examples in the tests here: https://github.com/httptoolkit/brotli-wasm/blob/47542a2d76bf87ce721fcceefe046b81b352c6e0/test/brotli.spec.ts#L105-L265

That's really just exposing the [underlying crate](https://crates.io/crates/brotli)'s own streaming API. No proper documentation yet, but PRs are very welcome!

**Comment by willfarrell** [comment]
Thanks, I'll try this approach out next weekend.
