### ISSUE TITLE
Having issues running Brotli in the browser

### ISSUE THREAD

**Issue by SchwiftyFella** [httptoolkit/brotli-wasm#24]
I am not sure if I am just making a simple mistake, but I am having trouble running this package when deployed. It works locally in my React dev environment but after deploying, I get this error:

 Cannot read properties of undefined (reading 't')
    at Object.XP9E (npm.brotli-wasm.bundle.3ebf91264addc48e56a6.js:1:1087)
    at b (runtime.bundle.d2efb756315d23783216.js:1:573)
    at Object.<anonymous> (npm.brotli-wasm.bundle.3ebf91264addc48e56a6.js:1:1621)
    at Object.nKSJ (npm.brotli-wasm.bundle.3ebf91264addc48e56a6.js:1:5223)
    at b (runtime.bundle.d2efb756315d23783216.js:1:573)
    at 81Yk (npm.brotli-wasm.bundle.3ebf91264addc48e56a6.js:1:108)
    at b (runtime.bundle.d2efb756315d23783216.js:1:573)
    XP9E @ npm.brotli-wasm.bundle.3    

I am using React, Webpack4 and babel. My code is below. Any help would be appreciated!
Code:
```javascript
import brotliPromise from 'brotli-wasm';

/**
 * decompressBrotli: convert byte array to a string using brotli decompression
 * @param input Byte array to decompress
 */
export async function decompressBrotli(input: string): Promise<string> {
  try {
    const brotli = await brotliPromise;
    const decodedVal = Buffer.from(input, 'base64');
    const decompressedData = brotli.decompress(decodedVal);
    if (!decompressedData) {
      throw new Error('Decompression failed');
    }
    const textDecoder = new TextDecoder('utf-8');
    const decodedString = textDecoder.decode(decompressedData);
    return decodedString;
  } catch (error) {
    console.error('Brotli decompression error:', error);
    throw error;
  }
}
```

**Comment by SchwiftyFella** [comment]
I figured it out the issue was with my webpack configuration. Also had to adjust my server configuration, this article was helpful: https://nicksnettravels.builttoroam.com/post-2019-03-20-publishing-uno-webassembly-wasm-to-azure-app-service-aspx/

Brotli-wasm works great though!

**Comment by pimterry** [comment]
Ok great @SchwiftyFella, glad to hear you got that working. I don't think I've seen this before myself, but if you think there's any key steps that are missing/need clarifying in the README here then do feel free to open a PR to add that in!
