### ISSUE TITLE
is v3 backward compatible with v2?

### ISSUE THREAD

**Issue by seidnerj** [httptoolkit/brotli-wasm#37]
Also, there are no equivalent releases in Github for v3 and v3.0.1. 

Thanks in advance!

**Comment by pimterry** [comment]
No it's not - the package follows semver. The only concrete breaking change in this case though was that we bumped the Node minimum engine requirement from v14 to Node v18. The package internals have also moved from Rust's Brotli package v3.3 to v5 - in theory that shouldn't make much visible difference as the external API we expose is still exactly the same, but there might subtle changes, dunno.

I've created a release to list those breaking changes more formally know, good suggestion. In general I'm not going to make a github release for every version (there's really not many changes, it's a tiny package and you can just look at the tags & commits) but I try to include breaking release details there to be explicit.

**Comment by seidnerj** [comment]
Awesome, thanks a lot!
