### ISSUE TITLE
Invalid types in brotli_wasm_bg.wasm.d.ts

### ISSUE THREAD

**Issue by stefnotch** [httptoolkit/brotli-wasm#9]
The file `brotli_wasm_bg.wasm.d.ts` that's published on `npm` has some (autogenerated) Typescript types which have a rather amusing issue:

The variable names are single letters, and after 26 variables, the entire alphabet is used up...

Line 36
```
export function BroccoliDestroyInstance(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number, u: number, v: number, w: number, x: number, y: number, z: number, {: number, |: number, }: number, ~: number, : number, : number, : number, : number, : number, : number, : number, : number, : number, : number, : number, : number, : number, : number, : number, : number, : number, : number, : number, : number, : number, : number, : number, : number, : number, : number, : number, : number, : number, : number, : number, : number, : number,  : number, ¡: number, ¢: number, £: number, ¤: number, ¥: number, ¦: number, §: number, ¨: number, ©: number, ª: number, «: number, ¬: number, ­: number, ®: number, ¯: number, °: number, ±: number, ²: number, ³: number, ´: number, µ: number, ¶: number, ·: number, ¸: number, ¹: number, º: number, »: number, ¼: number, ½: number, ¾: number, ¿: number, À: number, Á: number, Â: number, Ã: number, Ä: number, Å: number, Æ: number, Ç: number, È: number, É: number, Ê: number, Ë: number, Ì: number, Í: number, Î: number, Ï: number, Ð: number, Ñ: number, Ò: number, Ó: number, Ô: number, Õ: number, Ö: number, ×: number, Ø: number, Ù: number): void;
```

![image](https://user-images.githubusercontent.com/10220080/164488391-d725588a-fc52-47e0-a973-d36a21f7f98d.png)

**Comment by pimterry** [comment]
Hahaha, amazing, great find. Yes, that's a pretty convincing bug.

Unfortunately this is a wasm-pack issue again though I think. Can you open a bug over there? Happy to include any fixes here that I can, but those types are entirely autogenerated by wasm-pack.

**Comment by stefnotch** [comment]
Gladly! I'll let you know once I've opened it

**Comment by pimterry** [comment]
Oh neat! Ok, that's great. Do you know what wasm-pack version you're using? I'm happy to update & push a new release, that's fine.

> P.S. Thank you so much for making and maintaining this lovely library. It's super nice when it works and lets you do silly things like creating this https://stefnotch.github.io/url-catpressor/

Thanks, glad you're finding it useful! Great project :rofl:

**Comment by stefnotch** [comment]
Not entirely sure. I simply did `npm install`, which might have installed a newer minor version of wasm-pack.
Though, one could try upgrading all dependencies to their current version, test if it still works and go with that. Usually:tm: works out fine.

**Comment by pimterry** [comment]
Hmm, ok - the package.json version is `^0.9.1`, and that's the latest 0.9.* version that exists, so `npm install` shouldn't update anything.

There is a new 0.10 version, but I can't see anything related to this in their changelog and I've just updated to that and it doesn't seem to have changed anything - I still see the same output.

I'm testing this with:

```
> npm install
> rm -rf {node_modules,target,dist,pkg.*}
> npm run build
> less pkg.bundler/brotli_wasm_bg.wasm.d.ts
```

In that final `less` command I can see all the unicode characters in the signature of `BroccoliDestroyInstance` that you mentioned, even after updating.

Any idea what I'm missing here? Can you check what version of wasm-pack you're using (`npx wasm-pack --version`) and share the installed dependency versions (`npm ls`), and Node & Rust versions you're using?

**Comment by stefnotch** [comment]
Environment: Windows 10
Rust version: 1.55.0

Dependencies that got installed
```
C:\Users\Stefnotch\Desktop\temp\brotli-wasm-main>npm ls
brotli-wasm@1.1.0 C:\Users\Stefnotch\Desktop\temp\brotli-wasm-main
+-- @types/chai@4.3.1
+-- @types/mocha@8.2.3
+-- @types/node@15.14.9
+-- buffer@6.0.3
+-- chai@4.3.6
+-- karma-chai@0.1.0
+-- karma-chrome-launcher@3.1.1
+-- karma-mocha@2.0.1
+-- karma-sourcemap-loader@0.3.8
+-- karma-spec-reporter@0.0.32
+-- karma-typescript@5.5.3
+-- karma-webpack@5.0.0
+-- karma@6.3.19
+-- mocha@8.4.0
+-- shelljs@0.8.5
+-- ts-loader@9.2.8
+-- ts-node@9.1.1
+-- typescript@4.6.3
+-- wasm-pack@0.9.1
`-- webpack@5.72.0
```

**Comment by pimterry** [comment]
Found it! The issue was that there's two different sets of dependencies here: npm and Cargo. Cargo had a lock file on my machine locally that was gitignored, and defined the dependency version for wasm-bindgen, which is part of wasm-pack defines how these types get generated. 

Ignoring this lockfile in libraries is normally sensible, but not here, since this being a wasm package means it's effectively the end compile step for this code. Now fixed, I'll ship an updated brotli-wasm package to npm in 2 mins. Thanks for reporting this!

**Comment by stefnotch** [comment]
That's a sneaky bug indeed.
Thank you very much for taking your time to hunt it down. I can confirm that the issue is fixed!
